spring:
  security:
    user:
      name: itag
      password: itag
      roles: ADMIN
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  datasource:
    url: jdbc:mysql://localhost:3306/financialcontrol?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: rootd
    password: rootd
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 5000
  compression:
    enabled: true

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

logging:
  level:
    org.hibernate.SQL: DEBUG


app.jwtSecret: JWTSuperSecretKey
app.jwtExpirationInMs: 604800000